### PR TITLE
Added possibility to reduce memory footprint by turning off including and digitalWriteFast compat

### PR DESCRIPTION
**Pull request by 4ib3r**
Hi, i added possibility to exclude unused strategy files, and conditional definition to macro `__digitalPinToBit` (for MySensors library compatibility which already defines the same macro)

### CODE REVIEW

**Comment by gioblu** [comment]
Ciao @4ib3r thank you for your support to the project, will test soon 👍

**Comment by gioblu** [comment]
Ciao @4ib3r all seems fine, will be merged soon.

**Comment by gioblu** [comment]
Ciao @4ib3r digged a little further, I see that in mySensors there is an obsolete version of digitalWriteFast https://github.com/mysensors/MySensors/blob/815084b4faba3fcb42625d8b1c5881c2e3a25971/drivers/AVR/DigitalWriteFast/digitalWriteFast.h but as you can see is much more limited than ours, that has been extended porting: 

- ATmega8/88/168/328/1280/2560/16U4/32U4 (Duemilanove, Uno, Nano, Mini, Pro, Mega, Leonardo, Micro)
- ATtiny45/85 (Trinket / Digispark)
- SAMD21G18A (Arduino Zero)

Accepting your pull in this state could add bugs / communication loss on one of those devices because loosing the digitalWriteFast implementation present in our version. It would probably be nice to:
- Propose to MySensors team to make use of our version
- Change on our side nomenclature to avoid collision (also with other third party software using those obsolete versions of this early library)

**Comment by gioblu** [comment]
Ciao @4ib3r thank you for your support. I have accepted your pull, I made a naming change and moved docs in the documentation dir. I still have to figure out a new name for digitalWriteFast library and methods to avoid this sort of compatibility issues! Do you have any suggestions?

**Comment by 4ib3r** [comment]
Maybe the solution would be to add the prefix specific to a library such as "pjon_"

**Comment by gioblu** [comment]
Ciao @4ib3r what do you think about it?
It avoids the collision?

**Pull request merged**
