### PR TITLE
split definition and declaration for linux interface

### PR DESCRIPTION
**Pull request by mjasny**
Pull request for issue #130.

When using PJON in a more complex linux project only this statement has to be added and the corresponding .cpp file needs to be linked:
```
#define PJON_LINUX_SEPARATE_DEFINITION
#include <PJON.h>
```

### CODE REVIEW

**Comment by gioblu** [comment]
Ciao @mjasny thank you very much for your quick response :)

**Comment by gioblu** [comment]
Ciao @mjasny it seems all fine. 
Only one question, why you have removed the default initialization of `PJON_Packet_Info`?
That could give us trouble if not all members are explicitly set everywhere.

**Comment by mjasny** [comment]
Hi @gioblu 
sorry for that. I've removed this commit from this pull-request.

I had this fix for myself because I got the following compiler warning/error:

```
PJON/src/PJONDefines.h: In static member function 'static void PJONTools::parse_header(const uint8_t*, PJON_Packet_Info&)':
PJON/src/PJONDefines.h:264:33: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct PJON_Packet_Info'; use assignment or value-initialization instead [-Werror=class-memaccess]
  264 |     memset(&info, 0, sizeof info);
      |                                 ^
PJON/src/PJONDefines.h:195:8: note: 'struct PJON_Packet_Info' declared here
  195 | struct PJON_Packet_Info {
      |        ^~~~~~~~~~~~~~~~
```

**Comment by gioblu** [comment]
Ciao @mjasny thank you for pointing out the error, I will accept your pull request and fix this using assignment or value-initialization instead of `memset`

**Comment by gioblu** [comment]
Ciao @mjasny can I ask you to give a try to master?

I have pushed:
- Change .cpp to .inl to avoid arduino automatic inclusion (of all cpp files in src dir) (https://github.com/gioblu/PJON/commit/1b61529f4d9df112f5ca65f76f2828eaeabf57cf)
- Moved localhost to PJONTools (https://github.com/gioblu/PJON/commit/130ac7896e46a73c15492d8476ac289ca2832a3c)
- Fixed initialization to avoid the error you report while conserving consistency (https://github.com/gioblu/PJON/commit/5da78e0262d47af7f6cb58c8f2bbabc73f058baa)

**Comment by mjasny** [comment]
Hi @gioblu, looks and works fine for me :) Thanks!

Only one sidenote is that my AVR Sketch now occupies 8 more bytes of memory, but that is not a problem (yet) :)

**Comment by gioblu** [comment]
Ciao @mjasny yes, we got a slight footprint increase although now the parse function returns coherent meta-data also if used out of the operational environment of PJON. 

I plan to spare around 15 bytes of memory removing the internal random seed handling (setter and internal register), that will be responsability of the user. in LINUX you should just call `srand` before PJON's `begin`.

**Comment by gioblu** [comment]
Thank you again @mjasny,
Obviously, if you have in mind a better way to do the initialization sparing some memory feel free to share :)

**Pull request merged**
