### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by ibantxo**
Working better for me now

### CODE REVIEW

**Comment by ibantxo** [comment]
3 nodes sending "heartbeat" @ T=2s and no errors detected at the receiver.
About 300 messages sent:
node 1: 1 "connection lost" error
node 2: 131 "connection lost" error
node 3: 1 "connection lost" error
By now... No packet lost, no packet repeated.

**Comment by ibantxo** [comment]
switch(state) {
        case TSA_RESET: {
	  position = 0;
	  state = TSA_WAITING;  //<<<<<<<<<
        }

**Comment by gioblu** [comment]
Ciao @ibantxo going through the changes you propose:
- [here](https://github.com/gioblu/PJON/pull/271/files#diff-70e46edcb570da6597ffc2a7a0506cc8R375) I see here you inverted the position of the RS485 enable pin delays is that required to make it work? I think it was originally done so to let bytes have the time to go through the module before switching down the pin
- Not sure to understand [here](https://github.com/gioblu/PJON/pull/271/files#diff-70e46edcb570da6597ffc2a7a0506cc8R195) and the need to create the `TSA_RESET` state, looking at the code I see that `position` it is used only in the receiving states and set to 0 when reception starts [here](https://github.com/gioblu/PJON/pull/271/files#diff-70e46edcb570da6597ffc2a7a0506cc8L155) so I dont get how this can create you a problem or needs to be changed. Is this required for you to get a stable setup?
- I don't understand why [here](https://github.com/gioblu/PJON/pull/271/files#diff-70e46edcb570da6597ffc2a7a0506cc8R176) you need to avoid the return and use break to go blocking to reception afterwards, is this change effectively required to obtain a stable result?. This strategy is designed by @sticilface to supply an alternative to the blocking approach of ThroughSerial, in this case he postpones for the next loop the reception of bytes instead of breaking the while and go directly to the next case, this is useful to let the system work without interfering with other time sensitive operations running onboard (such as reading sensors or encoders).
- [Here](https://github.com/gioblu/PJON/pull/271/files#diff-70e46edcb570da6597ffc2a7a0506cc8R310) I agree we may wait twice the time effectively needed
- Sure is required [here](https://github.com/gioblu/PJON/pull/271/files#diff-70e46edcb570da6597ffc2a7a0506cc8R376) to update `_last_reception_time` considering that now we update it each time we receive a byte correctly?

I will push the changes suggested in the earlier pull, could you give a try to your setup with master (see https://github.com/gioblu/PJON/commit/957afa46a2d0889b5220b4a2397f425a560039de) and the successful `TSA_RESPONSE_TIME_OUT` configuration you spoke about in the chat?

Thank you very much for your support and feedback.

**Comment by ibantxo** [comment]
Hi @gioblu, thank you very much for your info. I will try to explain my status:

1. I have moved the baudrate from 115200 to 57600. I am testing now without RS485 bus. So I have connected directly a slave and the master. I am catching the bus traffic with ikalogic device. I have got captured correctly @ 57600 only. I am seeing that there is no ACK back. :-( Something wrong.
2. "inverted the position of the RS485 enable pin delays". I think it is better to wait after changing the transceiver state, not before. So... change, wait, READY TO TX, TX.... change, wait, READY TO RX, RX.
3. TSA_RESET is for debugging status.
4. _nonblocking_ vs blocking... If the received info is not mixed with other "collisioned" data, I think is better to empty the first entire packet from the serial bus. I do not think that is much more time required to do that work in one step or doing that work in smaller steps. I am not sure, I should meter those times to compare... My packets are very large... so I am testing this solution in order not to overflowing the serial <default> buffer.
5. _last_reception_time... I think it has to be updated at RX and at TX as well. This way, all the slaves has the same opportunities of TX. So, after a slave speaks all the slaves have the same "random" possibility to start speaking. Anyway, I think the best way to detect activity is not to change when receiving a byte. I think is better to detect it when there is a change at RX pin.
6. TSA_RESPONSE_TIME_OUT changes... it was the only way to avoid duplicated packets received at master. So just after receiving one packet, the same packet was received again at master (available serial data after getting the message). I have to test much more this point too...

I have to debugg much more... lol

Many thanks again, @gioblu

**Comment by ibantxo** [comment]
Detected why no ack received... It was received very late (50ms late), because set up... I have moved again to 1ms.

**Comment by gioblu** [comment]
Ciao @ibantxo duplicated packets happen in most cases because the receiver has not enough time to compute the packet and respond with an ack, and overshoot the timeout, for that reason it works setting a longer timeout, keep in mind that the longer is the packet, the longer timeout is required.

About the point 2, I was suspecting that,  maybe what you experience is related to the `TSA_RS485_DELAY` try to see if the result changes tweaking that.

Let me know how it goes with master, I am doing local tests here now.

Thank you very much :)

**Comment by ibantxo** [comment]
I have downloaded the last .zipped library from PJON.
I have connected directly 1 slave to the master, without RS485 bus:
scan002

**Comment by ibantxo** [comment]
imagen

**Comment by gioblu** [comment]
Ciao @ibantxo I have tested ThroughSerialAsync Blink and BlinkWithResponse examples using master.
It seems working as expected:

img_6918

Above you see the Blink example, so a packet containing B and the ACK (decimal 6) coming afer 680 microseconds.

img_6917

Above you see the BlinkWithResponse example, so a packet containing B the ACK, a response from receiver containing B and the ACK.

Could you include the program you have used so I can test it here?

**Comment by ibantxo** [comment]
OK. I think I have found something... I was using at slave and master this config to ensure that async ACK was properly configured: 

#define PJON_INCLUDE_PACKET_ID true
#define PJON_INCLUDE_ASYNC_ACK true
#define PJON_INCLUDE_TSA true   
#include <PJON.h>

inside setup():
pjon_bus.set_synchronous_acknowledge(false);
pjon_bus.set_asynchronous_acknowledge(true);

I have commented these lines:
#define PJON_INCLUDE_ASYNC_ACK true
pjon_bus.set_synchronous_acknowledge(false);
pjon_bus.set_asynchronous_acknowledge(true);

Now, the capture is this one:

**Pull request closed without merging**
