### PR TITLE
Update Receiver.ino

### PR DESCRIPTION
**Pull request by Radiusxe**
replaced digitalWrite to digitalWriteFast

### CODE REVIEW

**Comment by gioblu** [comment]
Ciao @Radiusxe thank you for your support. Is this change related to general consistency in the use of the digitalWriteFast method evertwhere in the library or to a timing related issue?

**Comment by Radiusxe** [comment]
Hi,
its just cosmetics.

Radius

**Comment by gioblu** [comment]
Ciao @Radiusxe, thank you again. Accepting 👍

**Comment by Radiusxe** [comment]
Hi,
thanks.
Radius

**Pull request merged**
