### PR TITLE
Added support for AtMega1284P

### PR DESCRIPTION
**Pull request by fabpolli**
Added support for AtMega1284P, tested with Serial strategy. I'll test SoftwareBitBang soon

### CODE REVIEW

**Comment by gioblu** [comment]
Thank you @fabpolli for your support, I will wait for the test results.

**Comment by gioblu** [comment]
Ciao @fabpolli thank you so much for your support.

I wrote down this sort of basic description to explain to another contributor how the `PJON_IO_PIN_TO_BIT` method works and how is related to register bits, hope this could help you:

At line https://github.com/gioblu/PJON/blob/master/interfaces/ARDUINO/PJON_IO.h#L258
bitWrite is used to set a certain bit in a variable passing:
- The number in which to write
- The index of the bit where to write (starting at 0 for the least-significant or rightmost bit)
- The value (0 or 1)
```cpp
// sets x to 33 (00100001 in binary) 
byte x = 33;  
// writes a 1 to the second bit bit of x, now x is 00100101 (37 in decimal) 
bitWrite(x, 2, 1);
```
So `PJON_IO_PIN_TO_BIT` should return for a given pin which bit index should be set accordingly in the register. To make a simple example if you look the ATtiny85 datasheet (http://www.farnell.com/datasheets/1698186.pdf) at page 63 (10.4) you can see the address bits table. For example for PB0 the first rightmost bit should be returned and so should be passed to bitWrite 0, in this particular case the pin number passed: `PJON_IO_WRITE(0)` is also the correct bit index to be set in the register, so the macro is simply: https://github.com/gioblu/PJON/blob/master/interfaces/ARDUINO/PJON_IO.h#L144

Before accepting your pull I would be sure that for the requested pin state/mode is set/read correctly, if you have the time, a simple test with a LED and pin state reading test, I sadly do not have here this MCU but I will soon buy it for local testing. Thank you again for your support.

**Comment by fabpolli** [comment]
Ciao @gioblu I understood how PJON use this information. I commited a more smart define of pin assignment but unfortunately Bitbang still doesn't work correctly.
Actually it work on pin D0,D1,D2,D5 and from D18 to D31 (18-23+A0-A7), so all pins of PORTA, from 2 to 7 of PORTC, 0 to 2 and 5 of PORTB and non of PORTD, but I never give up and I will do other test. If You ave any suggestions...

**Comment by gioblu** [comment]
Ciao @fabpolli, thank you so much for your support. It does work with the default timing?
Not all pins on all mcus are compatible because of difference in execution time.
Maybe a test to the non working pins can help to assess if the pin setting and reading procedure is happening as intended.

**Comment by fabpolli** [comment]
Ciao @gioblu for test purpose I've used Your example (PJON->ARDUINO->Local->SoftwareBitBang->BlinkWithResponse)
Trasmitter on an Arduino Uno, receiver on 1284P. I've made some customization on receiver for put new pin number directly on Serial monitor, change only pin number, compile and upload new program is boring!
But for extreme caution I've tested some unfunctional pins without serial reading (standard way, change, compile and upload) without success.
When I test Serial pins I remove all "Serial" reference in program and if I try pin 13 I remove pinMode and all digitalWrite on that pin. On that pin when I start to send data from transmitter it flashing repeatly and rapidly but PJON does't receive data and in serial monitor dont appear "BLINK" it's a usefult information?

**Comment by gioblu** [comment]
Ciao @fabpolli, thank you for your support.
If you see flashes but no reception on pin 13, it means data is transmitted but not received correctly by the receiver. The last test could have sense to try is networkAnalysis if you can. 

Then I think I can merge this pull reporting the pins where communication is reliable while waiting for the ATmega1284P to arrive here :)

**Comment by gioblu** [comment]
Ciao @fabpolli I will accept now your proposal because I will then need to change the dir structure and I would avoid to force you to close this and open a new pull request. Feel free to work on the files after that if needed. Thank you again.

**Pull request merged**
