### PR TITLE
STM32 Workarround for missing ethernet refernces

### PR DESCRIPTION
**Pull request by chestwood96**
Excludes Ethernet from default strategies because of missing references (like ATtiny85).

Workaround so the examples compile at least until STM32 Ethernet gets fixed.

This only excludes STM32F1.

### CODE REVIEW

**Comment by chestwood96** [comment]
So far this only works with the github install of STM32duino, I have not found the right define for the wiki version

**Comment by chestwood96** [comment]
This should work for both now

**Comment by gioblu** [comment]
Ciao @chestwood96 thank you very much for your support and sorry for the late response.
Thank you for pointing out this compilation error.

Looking back at `PJON_strategies.h` I initially have settled to have all strategies included for convenience and not to use conditionals and hardware related constants, although at the end we ended up needing those to exclude particular cases. 

Reasoning about it: https://github.com/gioblu/PJON/blob/master/src/strategies/PJON_Strategies.h

A way to avoid this sort of compilation error, specially when porting a new device or using an early support could be to conditionally include only the working strategies if a particular hardware constant is defined. Although the file would become much more complex. 

```cpp
#if defined(__AVR_ATtiny45__) && defined(__AVR_ATtiny85__) && \
      defined(__AVR_ATtiny44__) && defined(__AVR_ATtiny84__)
    #include "SoftwareBitBang/SoftwareBitBang.h"
    #include "AnalogSampling/AnalogSampling.h"
    #include "OverSampling/OverSampling.h"
  #endif 
```
So include only the supported strategies for each supported hardware, instead of what is done today, or conditionally not include certain strategies if certain hardware constants are defined. The pro is that code a new port or for an early support would less likely fail because of a compilation error of this sort. 


What do you think?

**Comment by chestwood96** [comment]
TBH I would probably go with option 3 and not include any at all and manually include them in the examples.

There is also the option of conditionally enabling the Ethernet based ones  (as they seem to require a lot more plumbing than the others)  on platforms that support it and leaving them disabled by default.

All options feel kind of suboptimal to me though.

**Comment by gioblu** [comment]
Yes probably a separate issue is required to discuss more in detail this issue and find the best solution.
I will accept your pull so at least for now compiles fine, until we have not decided.
Thank you again for your support.

**Pull request merged**
